Boolean prop casting should use default value
vuejs/vue-web-component-wrapper pull request #58
Opened 2019-09-06 16:14 UTC by sylvainpolletvillard

fix #3 

the PR includes some formatting changes, they have been automatically done with the pre-commit lint-staged git hook, so I did not remove them :confused:

2019-09-06 16:15 UTC, sylvainpolletvillard commented on test/test.js
> +/* global test expect el els */
I needed to add this to pass the lint-staged pre-commit git hook

2019-09-08 04:59 UTC, sodatea commented
Then how do you pass `false` to this property?
I don't think this is a practical solution.

2019-09-08 11:24 UTC, sylvainpolletvillard commented
This does not change how `false` behaves, `return value != null` was already returning true for `value=false`

But I agree we should add more tests. If boolean prop default is an antipattern, it should still be handled the same way between Vue and vue-web-component-wrapper.

2021-01-20 16:06 UTC, m-mohr commented
I'm also facing this issue and would appreciate it if this gets merged.

2021-02-11 13:19 UTC, m-mohr commented
@sodatea Is this project dead or why is a simple bug fix not merged after around 1.5 years? Do we really need to fork this repo and vue-cli to get such annoying bugs fixed? They change the behavior of apps.

2021-02-11 13:40 UTC, sodatea commented
Because I'm opposed to this design and I'm not persuaded by previous comments.

It's not a bug fix anyway.

2021-02-11 13:46 UTC, m-mohr commented
@sodatea How is this not a bug if you have a component that has different default values in different environments?

If I have a prop with default value true, compile it normally (e.g. as lib) and don't set a value for the prop, the value is actually true. (Good)
If I compile as web component, the value is FALSE! I can't imagine any valid argument that this is working as expected?!

This is a huge concern. For example, I have a prop "disallowHTML", which now allows HTML in web components and people can do XSS attacks!

If you want to enforce that al Boolean props must have a default of false, then don't allow specifying default values in this case.

2021-02-11 14:02 UTC, sodatea commented
I'm not sure if it is in the spec but it's surely a common practice in the industry. Here's the documentation from the polymer project: https://polymer-library.polymer-project.org/3.0/docs/devguide/properties#configuring-boolean-properties

2021-02-11 14:04 UTC, sodatea commented
I'd recommend a "allowHTML" property instead for that particular use case.

2021-02-11 14:06 UTC, m-mohr commented
@sodatea Yeah, but that doesn't help for people that have a library that is exposed both as SFC and Web Components. Then you need to write in your documentation: If you use web components, default value is "false, otherwise "true". 

And no, I won't break a lot of implementations with such a change to work around a bug in this library.

2021-02-11 14:07 UTC, sodatea commented
> This does not change how `false` behaves, `return value != null` was already returning true for `value=false`
> 
> 
> 
> But I agree we should add more tests. If boolean prop default is an antipattern, it should still be handled the same way between Vue and vue-web-component-wrapper.

Forgot to reply to this earlier. `value=false` is not possible in the HTML markup. You have to use JavaScript for that use case, which is extremely counterintuitive.

2021-02-11 14:08 UTC, sylvainpolletvillard commented
For information, Vue 3 has [still the same behaviour](https://codesandbox.io/s/competent-nash-cjyjm?file=/src/components/MyButton.vue) that applies boolean default `true` values when prop is omitted.

If this is "antipattern" or "common practice in the industry", why did they keep it that way in Vue 3 ?

This projects is supposed to be a wrapper, and a wrapper is not supposed to change the behaviour of what's inside.

2021-02-11 14:09 UTC, sodatea commented
> And no, I won't break a lot of implementations with such a change to work around a bug in this library. We just recently introduced web components and it obviously wasn't a good choice as the Vue tooling for web components is really buggy.

I'm afraid you might end up in the exact same situation with most other web component wrappers, not just in the Vue ecosystem.

2021-02-11 14:12 UTC, m-mohr commented
@sodatea I only know one additional web component wrapper, the one by karolf and it doesn't have this issue. There the default values work just fine!

> > This does not change how `false` behaves, `return value != null` was already returning true for `value=false`
> > But I agree we should add more tests. If boolean prop default is an antipattern, it should still be handled the same way between Vue and vue-web-component-wrapper.
> 
> Forgot to reply to this earlier. `value=false` is not possible in the HTML markup. You have to use JavaScript for that use case, which is extremely counterintuitive.

Why is that? Can't I pass `attr="false"` to a HTML tag?

2021-02-11 14:15 UTC, sodatea commented
> For information, Vue 3 has [still the same behaviour](https://codesandbox.io/s/competent-nash-cjyjm?file=/src/components/MyButton.vue) that applies boolean default `true` values when prop is omitted.
> 
> 
> 
> If this is "antipattern" or "common practice in the industry", why did they keep it that way in Vue 3 ?
> 
> 
> 
> This projects is supposed to be a wrapper, and a wrapper is not supposed to change the behaviour of what's inside.

- It's not an antipattern in the context of Vue components. Because both Vue template and JSX syntaxes accept rich data, while HTML markup does not.

2021-02-11 14:17 UTC, sodatea commented
> Why is that? Can't I pass `attr="false"` to a HTML tag?

It would be interpreted as a string.

2021-02-11 14:20 UTC, m-mohr commented
> > Why is that? Can't I pass `attr="false"` to a HTML tag?
> 
> It would be interpreted as a string.

@sodatea Yes, indeed and to handle this you have code to convert it to a boolean in the code:
```
export function convertAttributeValue (value, name, { type } = {}) {
  if (isBoolean(type)) {	  if (isBoolean(type)) {
    if (value === 'true' || value === 'false') {
```
So it's possible - you've implemented it. Your argument seems invalid.

2021-02-11 14:21 UTC, m-mohr commented
> It's not an antipattern in the context of Vue components. Because both Vue template and JSX syntaxes accept rich data, while HTML markup does not.

So you think it's reasonable that default values for properties are different if you expose both SFC and web components? That seems like the bigger anti-pattern to me.

2021-02-11 14:32 UTC, sodatea commented
> > > Why is that? Can't I pass `attr="false"` to a HTML tag?
> 
> > 
> 
> > It would be interpreted as a string.
> 
> 
> 
> @sodatea Yes, indeed and to handle this you have code to convert it to a boolean in the code:
> 
> ```
> 
> export function convertAttributeValue (value, name, { type } = {}) {
> 
>   if (isBoolean(type)) {	  if (isBoolean(type)) {
> 
>     if (value === 'true' || value === 'false') {
> 
> ```
> 
> So it's possible - you've implemented it. Your argument seems invalid.

Oops, sorry, I totally forgot about this. Maybe I mistakenly mix this PR up with another one that adds array support so that I didn't merge either. Give me a moment and I'll re-review this PR.

I'm still opposed to this pattern but maybe worth fixing the behavior.

2021-02-11 14:35 UTC, sodatea commented
> > It's not an antipattern in the context of Vue components. Because both Vue template and JSX syntaxes accept rich data, while HTML markup does not.
> 
> 
> 
> So you think it's reasonable that default values for properties are different if you expose both SFC and web components? That seems like the bigger anti-pattern to me.
> 
> 
> 
> 

IMO, if it's only intended for usage in Vue components, it's "not recommended", but in web components, it's "strongly against". Different levels of opposition.

2021-02-11 15:44 UTC, sodatea requested changes
A few small refinements required. Thanks.

2021-02-11 15:44 UTC, sodatea commented on test/fixtures/attributes.html
> +<my-element foo="foo" bar="true" some-number="123"></my-element>
Please add a test case for setting `false` on a default `true` boolean property here.
Also, please don't delete the final newline.

2021-02-11 15:44 UTC, sodatea commented on test/fixtures/attributes.html
> +  import wrap from '../../src/index.js'
Unnecessary indentation.

2021-02-11 15:47 UTC, m-mohr commented on test/fixtures/attributes.html
> +<my-element foo="foo" bar="true" some-number="123"></my-element>
@sylvainpolletvillard Do you have time to make the requested changes? Otherwise, I'd be happy to help you somehow, e.g. by PRing the changes to your repo.

2021-02-11 15:47 UTC, sylvainpolletvillard commented on test/fixtures/attributes.html
> +  import wrap from '../../src/index.js'
as I said in the PR description, these formatting changes have been automatically done with the pre-commit lint-staged git hook. I have no control on that

2021-02-11 15:49 UTC, sodatea commented
I plan to release a new version later tomorrow or the day after tomorrow.

Because it's Lunar New Year's Eve now in China. If too many people have relied on the previous behavior and thus this small patch breaks their apps, I need to make sure I can revert it back soon.

Anyway, thanks for the discussion and contributions. Happy Lunar New Year!

2021-02-11 15:55 UTC, sodatea commented on test/fixtures/attributes.html
> +  import wrap from '../../src/index.js'
🤔 Maybe it's because there's an ESLint config in the package.json but missing the `root: true` field, so ESLint merges it with one in an upper-level directory.

For now, you can use `git commit --no-verify` to temporarily work around it.

2021-02-11 16:03 UTC, m-mohr commented
For the sake of completeness (or if this doesn't get merged or reverted), here's a code snippet that tries it's best to revert to the actual default value for Boolean values.

```
function fixBooleanDefaults(vm) {
        // Don't execute if not in web-component mode (i.e. check for the shadow root)
        if (!Utils.isObject(vm.$parent) || !vm.$parent.$options.shadowRoot) {
            return;
        }

        // Workaround for bug https://github.com/vuejs/vue-web-component-wrapper/issues/3
        // PR: https://github.com/vuejs/vue-web-component-wrapper/pull/58
        if (Utils.isObject(vm.$options.props)) {
            for(let prop in vm.$options.props) {
                let schema = vm.$options.props[prop];
                let hasAttribute = vm.$parent.$options.shadowRoot.host.hasAttribute(Utils.camelToKebabCase(prop));
                console.log(prop, hasAttribute);
                if (schema.default === true && !hasAttribute) {
                    vm.$options.propsData[prop] = true;
                }
            }
        }
}
```

Call it in beforeCreate: `fixBooleanDefaults(this)`

2021-02-11 16:36 UTC, sylvainpolletvillard commented
Remarks fixed.

> If too many people have relied on the previous behavior and thus this small patch breaks their apps

that means these people were relying on a behaviour that is already specific to vue-web-component-wrapper, and gives the opposite boolean value when used as a Vue component. I think this situation is much more dangerous and prone to footguns that my patch proposal.

2021-02-12 06:58 UTC, sodatea commented
> that means these people were relying on a behaviour that is already specific to vue-web-component-wrapper, and gives the opposite boolean value when used as a Vue component. I think this situation is much more dangerous and prone to footguns that my patch proposal.

Yeah, but bad things can happen - I have experiences that a harmless bugfix made lots of people mad at me. So I want to make sure I can fix it when unintended consequences do appear.

2021-02-13 11:23 UTC, sodatea approved these changes

2021-02-13 11:24 UTC, merged

2021-02-13 11:47 UTC, sodatea commented
Released as 1.3.0 because there are some other previously unpublished commits: https://github.com/vuejs/vue-web-component-wrapper/releases/tag/v1.3.0

2021-02-15 09:27 UTC, m-mohr commented
Great, thanks! I guess this becomes directly available with the next vue-cli release?

2021-02-16 04:37 UTC, sodatea commented
As Vue CLI uses caret ranges, I think deleting the lockfile and reinstalling the dependencies would suffice to get the latest release.